### ISSUE TITLE
New filter condition

### ISSUE THREAD

**Issue by moodyblue** [CutePoisonX/PoisonConvert#7]
Hi again, I've seen that you have included in AppleTV3 the capability to reencode the file. I would like to use that possibility but for short duration films only, otherwise the conversion of a single film could take days in the Syno, and I prefer in these cases to upload the file to my PC and use Handbrake instead.

But for this to work I would like to have a new selection parameter. Would this be possible in a future release ?

**Comment by CutePoisonX** [comment]
Hi! I could add a rule for the duration of the movie so you can select on a per-config base when you want to include a video that has less than a specified duration.
What I could do also is adding a setting where you can specify to write all videos that were not processed in a single file.
You then could write a script that takes this file and moves every video in the that to your computer.
I think this would be a nice option since its kind of universal (you can do everything you want with that list) and you can add several durations in different configurations.
Unfortunately this won't make it into v1.4.1, but it would be first priority of the following release.

What do you think about it?

**Comment by moodyblue** [comment]
Thanks for your fast reply. Regarding the rule for movie duration, it's a
great idea, specially if we can combine it with the bitrate.

Regarding the creation of a separate file with the names of non-converted
files, to be honest I do not have the skill to make use of it, but I think
that it can be usefull to others.

Cheers

2015-06-02 19:00 GMT+01:00 CutePoisonX <notifications@github.com>:

**Comment by moodyblue** [comment]
My Syno crashed, now I'm using QNAP instead.
